# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(unique=True, serialize=False, primary_key=True)),
                ('gender', models.CharField(null=True, blank=True, max_length=7, choices=[(b'm', b'Male'), (b'f', b'Female'), (b'o', b'Other')])),
                ('year', models.IntegerField(blank=True, null=True, choices=[(98, 1998), (99, 1999), (0, 2000), (1, 2001), (2, 2002), (3, 2003), (4, 2004), (5, 2005), (6, 2006), (7, 2007), (8, 2008), (9, 2009), (10, 2010), (11, 2011), (12, 2012), (13, 2013), (14, 2014), (15, 2015), (16, 2016), (17, 2017), (18, 2018), (19, 2019), (20, 2020)])),
                ('dob', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('ph_no', models.CharField(max_length=15, null=True)),
                ('program', models.CharField(blank=True, max_length=10, null=True, choices=[(b'b', b'B.Tech.'), (b'm', b'M.Tech.'), (b'bd', b'B.Des.'), (b'p', b'Ph.D.'), (b'other', b'Other')])),
                ('dept', models.CharField(null=True, blank=True, max_length=25, choices=[(b'bt', b'Biotechnology [BT]'), (b'cl', b'Chemical [CL]'), (b'che', b'Chemistry [CHE]'), (b'ce', b'Civil [CE]'), (b'cse', b'Computer Science [CSE]'), (b'ds', b'Design [DD]'), (b'eee', b'Electrical [EEE]'), (b'ece', b'Electronics [ECE]'), (b'hss', b'Humanities &amp; Social Sciences [HSS]'), (b'ma', b'Mathematics [MA]'), (b'me', b'Mechanical [ME]'), (b'ep', b'Physics [EP]'), (b'cfe', b'Centre for Energy'), (b'cfte', b'Centre for the Environment'), (b'cnt', b'Centre for Nanotechnology'), (b'o', b'Other')])),
                ('guide', models.CharField(max_length=25, null=True, blank=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('alt_email', models.CharField(max_length=50, null=True)),
                ('rg_link', models.CharField(max_length=250, null=True, blank=True)),
                ('cur_adrs', models.CharField(null=True, max_length=200)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=25, null=True, blank=True)),
                ('pin', models.IntegerField(null=True)),
                ('alt_mob', models.CharField(max_length=15, null=True, blank=True)),
                ('l_link', models.CharField(max_length=250, null=True, blank=True)),
                ('per_adrs', models.CharField(max_length=200, null=True)),
                ('per_city', models.CharField(max_length=25, null=True)),
                ('per_country', models.CharField(max_length=25, null=True, blank=True)),
                ('per_pin', models.IntegerField(null=True)),
                ('cur_position', models.CharField(max_length=150, null=True, choices=[(b'scholar', b'Scholar'), (b'job', b'Job'), (b'startup', b'Startup/NGO'), (b'other', b'Other')])),
                ('past_position_1', models.CharField(max_length=150, null=True, blank=True)),
                ('past_position_2', models.CharField(max_length=150, null=True, blank=True)),
                ('past_position_3', models.CharField(max_length=150, null=True, blank=True)),
                ('details', models.CharField(max_length=150, null=True, blank=True)),
                ('details_1', models.CharField(max_length=150, null=True, blank=True)),
                ('details_2', models.CharField(max_length=150, null=True, blank=True)),
                ('details_3', models.CharField(max_length=150, null=True, blank=True)),
                ('startup', models.CharField(max_length=400, null=True, blank=True)),
                ('imp_link_2', models.CharField(max_length=150, null=True, blank=True)),
                ('imp_link_3', models.CharField(max_length=150, null=True, blank=True)),
                ('any_1', models.CharField(max_length=150, null=True, blank=True)),
                ('any_2', models.CharField(max_length=150, null=True, blank=True)),
                ('any_3', models.CharField(max_length=150, null=True, blank=True)),
                ('hostel', models.CharField(null=True, blank=True, max_length=15, choices=[(b'Barak', b'Barak'), (b'Brahmaputra', b'Brahmaputra'), (b'Dhansiri', b'Dhansiri'), (b'Dibang', b'Dibang'), (b'Dihing', b'Dihing'), (b'Kameng', b'Kameng'), (b'Kapili', b'Kapili'), (b'Lohit', b'Lohit'), (b'Manas', b'Manas'), (b"Married Scholar's Hostel", b"Married Scholar's Hostel"), (b'Siang', b'Siang'), (b'Subansiri', b'Subansiri'), (b'Umiam', b'Umiam'), (b'Other', b'Other')])),
                ('room_no', models.CharField(max_length=10, null=True, blank=True)),
                ('campus_involvements_1', models.CharField(max_length=200, null=True, blank=True)),
                ('campus_involvements_2', models.CharField(max_length=200, null=True, blank=True)),
                ('staged_at', models.IntegerField(null=True, blank=True)),
                ('position', models.TextField(null=True)),
                ('position_1', models.CharField(max_length=30, null=True, blank=True)),
                ('position_2', models.CharField(max_length=30, null=True, blank=True)),
                ('city_1', models.CharField(max_length=50, null=True)),
                ('city_2', models.CharField(max_length=50, null=True, blank=True)),
                ('city_3', models.CharField(max_length=50, null=True, blank=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('company_1', models.CharField(max_length=100, null=True, blank=True)),
                ('company_2', models.CharField(max_length=100, null=True, blank=True)),
                ('guidance', models.IntegerField(null=True, blank=True)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('about_you', models.TextField(null=True, blank=True)),
                ('facebook_link', models.URLField(null=True, blank=True)),
                ('github_link', models.URLField(null=True, blank=True)),
                ('google_link', models.URLField(null=True, blank=True)),
                ('last_name', models.CharField(max_length=50, null=True, blank=True)),
                ('middle_name', models.CharField(max_length=50, null=True, blank=True)),
                ('other_interests', models.TextField(null=True, blank=True)),
                ('profile_picture', models.ImageField(null=True, upload_to=b'Images', blank=True)),
                ('title', models.CharField(max_length=5, null=True, blank=True)),
                ('twitter_link', models.URLField(null=True, blank=True)),
                ('videos_list', models.TextField(null=True, blank=True)),
                ('your_message', models.TextField(null=True, blank=True)),
            ],
        ),
    ]
